######################################################################
##
## Filename: CPU_Pipeline.udo
## Created on: Tue Jul 21 15:45:46 中国标准时间 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
